deployment:
  name: webapp
  containerPort: 80
  label: webapp
  image: europe-west3-docker.pkg.dev/vaulted-bit-384519/diplomski/my-awesome-project/webapp:latest
  replicas: 2

service:
  name: webapp-svc
  port: 80
  type: LoadBalancer
